spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux_practice
    username: root
    password: admin123
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql