spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux_practice
    username: root
    password: admin123
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

aws:
  region: us-east-1
  sns:
    topicArn: arn:aws:sns:us-east-1:000000000000:user-created-topic
